name: Java-CI
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
jobs:
  Clone-down:
    name: Clone repo
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Upload code artifact
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  Test:
    name: Test
    runs-on: ubuntu-latest
    needs: Clone-down
    container: gradle:6-jdk11
    steps:
      - name: Download code artifact
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: Test app
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
  Build:
    name: Build
    runs-on: ubuntu-latest
    needs: Clone-down
    container: gradle:6-jdk11
    steps:
      - name: Download code artifact
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: Build app
        run: chmod +x ci/build-app.sh && ci/build-app.sh
      - name: Upload code artifact
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  Docker-image:
    name: Docker image
    runs-on: ubuntu-latest
    needs: [Build,Test]
    steps:
    - name: Download code artifact
      uses: actions/download-artifact@v2
      with:
        name: code
        path: .
    - name: Build docker image
      run: chmod +x ci/build-docker.sh && export GIT_COMMIT="GA-$GITHUB_SHA" && ci/build-docker.sh
    - name: Push image to docker
      run: chmod +x ci/push-docker.sh && export GIT_COMMIT="GA-$GITHUB_SHA" && ci/push-docker.sh
  Component-test:
    name: Component test
    runs-on: self-hosted
    needs: Docker-image
    steps:
    - name: Download code artifact
      uses: actions/download-artifact@v2
      with:
        name: code
        path: .
    - name: Component test
      run: chmod +x ci/component-test.sh && GIT_COMMIT="GA-$GITHUB_SHA" && ci/component-test.sh